language: go
sudo: false
matrix:
  include:
    - go: "1.10.x"
      script:  go test -v ./...
    - go: "1.11.x"
      script: go test -v -mod=vendor ./...
os:
  - osx
  - linux
notifications:
  email:
    recipients:
      - archer.vanderwaal@gmail.com
    on_success: always
    on_failure: always
env:
  - GO111MODULE=on
install: true